---
- name: copy files
  copy:
    src: files/opt/
    dest: /opt/
    owner: root
    group: svc
    mode: preserve
    force: yes
    directory_mode: u=rwx,g=rx,o=

- name: install confd files
  include_role:
    name: confd-files-1.0.9

- name: install services
  copy:
    force: yes
    src: "{{ role_path }}/files/lib/systemd/system/"
    dest: /lib/systemd/system/

- name: mask services
  systemd:
    name: "{{ service_name }}"
    enabled: no
    masked: yes
    state: stopped
  loop:
  - redis-server
  - redis-sentinel
  loop_control:
    loop_var: service_name